-- 台风路径预报图记录表
-- 数据库: zjtyphoon (达梦DM, 10.91.2.104:8822)
CREATE TABLE TYPHOON_PROB_IMG (
    TF_CODE   VARCHAR(20)  NOT NULL,   -- 台风编号, 如 "202613"
    TF_NAME   VARCHAR(100),            -- 台风名称, 如 "白海豚"
    IMG_TIME  VARCHAR(20)  NOT NULL,   -- 图片时间, 如 "2026-07-31 11:00:00"
    IMG_PATH  VARCHAR(500),            -- 本地存储路径
    IMG_URL   VARCHAR(500),            -- 原始CDN URL
    PRIMARY KEY (TF_CODE, IMG_TIME)
);

COMMENT ON TABLE TYPHOON_PROB_IMG IS '台风路径预报图记录表';
COMMENT ON COLUMN TYPHOON_PROB_IMG.TF_CODE IS '台风编号';
COMMENT ON COLUMN TYPHOON_PROB_IMG.TF_NAME IS '台风名称';
COMMENT ON COLUMN TYPHOON_PROB_IMG.IMG_TIME IS '图片时间';
COMMENT ON COLUMN TYPHOON_PROB_IMG.IMG_PATH IS '本地存储路径';
COMMENT ON COLUMN TYPHOON_PROB_IMG.IMG_URL IS '原始CDN URL';
